//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelAPIStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_Ventas
    {
        public int id_detalle_venta { get; set; }
        public int id_producto { get; set; }
        public int id_venta { get; set; }
        public Nullable<bool> suspencion { get; set; }
        public Nullable<System.DateTime> fecha_suspencion { get; set; }
    
        public virtual Productos Productos { get; set; }
        public virtual Ventas Ventas { get; set; }
    }
}
