//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelAPIStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Factura()
        {
            this.Despachos_Electronico = new HashSet<Despachos_Electronico>();
        }
    
        public int id_factura { get; set; }
        public int id_venta { get; set; }
        public System.DateTime fecha_facturacion { get; set; }
        public int id_direccion { get; set; }
        public int iva_actual { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Despachos_Electronico> Despachos_Electronico { get; set; }
        public virtual Direccion Direccion { get; set; }
        public virtual Ventas Ventas { get; set; }
    }
}
