//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelAPIStore
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class APIStoreEntities1 : DbContext
    {
        public APIStoreEntities1()
            : base("name=APIStoreEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ciudades> Ciudades { get; set; }
        public virtual DbSet<Despachos_Electronico> Despachos_Electronico { get; set; }
        public virtual DbSet<Direccion> Direccion { get; set; }
        public virtual DbSet<Factura> Factura { get; set; }
        public virtual DbSet<Lenguaje_Backend> Lenguaje_Backend { get; set; }
        public virtual DbSet<Paises> Paises { get; set; }
        public virtual DbSet<Productos> Productos { get; set; }
        public virtual DbSet<Regiones> Regiones { get; set; }
        public virtual DbSet<Tipo_Licencias> Tipo_Licencias { get; set; }
        public virtual DbSet<Imagenes> Imagenes { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
        public virtual DbSet<Detalle_Ventas> Detalle_Ventas { get; set; }
        public virtual DbSet<Ventas> Ventas { get; set; }
    }
}
